#!/usr/bin/env python3
"""
Heraldor — ZapeG'in karanlık varlığı (v2: persistent director).

Herobrine türü bir varlık ama bizimki: adı Heraldor. Kimse ondan bahsetmez,
o herkesi izler. Bu servis rastgele ve NADİR olaylar üretir:

  whisper  — rastgele bir oyuncuya, sadece onun gördüğü fısıltı (+ ürkütücü ses)
  global   — herkese kısa, şifreli bir cümle (çok nadir)
  discord  — Discord kanalına imzasız/tekinsiz mesaj (webhook; en nadiri)
  shadows  — [VARSAYILAN KAPALI] gece yarısı, rastgele bir oyuncunun yanına
             30 saniyeliğine "Heraldor'un Gölgesi" adlı 3 vex (kendiliğinden yok
             olur — korkutur, eşya/ev zararı yok)

KubeJS'in gizli skor tahtasındaki ``Heraldor'un Hizmetkârı`` zaferleri ayrıca
izlenir. SQLite yüksek-su işareti ve tek-seferlik hikâye bayrağı sayesinde
yeniden başlatmalar aynı eşiği tekrar çalıştırmaz.

Gece (oyun saati 13000–23000) fısıltı olasılığı 3 katına çıkar.
LLM opsiyoneldir (HERALDOR_LLM=true + LLM_* env): satırlar üretilir; kapalıysa
gömülü havuzlar kullanılır. Asla oyuncu girdisi komut olarak çalıştırılmaz.
"""
import argparse
import json
import os
import random
import re
import time
import urllib.request
from dataclasses import dataclass
from pathlib import Path

from mcrcon import MCRcon

from heraldor_director import (
    CONTROL_PHASES,
    CONTROL_SCENE_PROFILE_PHASES,
    CONTROL_TOKEN_MAX_FUTURE_SECONDS,
    ControlRequest,
    DirectorStateLock,
    DirectorStore,
    Reservation,
    extract_control_request_token,
    parse_control_request,
    parse_score_output,
    restore_snapshot,
    scene_ttl_ticks,
)

RCON_HOST = os.environ.get("RCON_HOST", "mc")
RCON_PORT = int(os.environ.get("RCON_PORT", "25575"))
RCON_PASSWORD_OVERRIDE = os.environ.get("RCON_PASSWORD", "").strip()
RCON_ENV_FILE = Path(os.environ.get("RCON_ENV_FILE", "/run/secrets/mc-rcon.env"))
WEBHOOK = os.environ.get("HERALDOR_WEBHOOK", "").strip()
EVENTS = os.environ.get("HERALDOR_EVENTS", "false").lower() == "true"
USE_LLM = os.environ.get("HERALDOR_LLM", "false").lower() == "true"
VOICE_ENABLED = os.environ.get("HERALDOR_VOICE_ENABLED", "false").lower() == "true"
CHECK_INTERVAL = max(10, int(os.environ.get("CHECK_INTERVAL", "300")))
MINION_POLL_INTERVAL = max(5, int(os.environ.get("MINION_POLL_INTERVAL", "10")))
CONTROL_POLL_INTERVAL = max(1, int(os.environ.get("CONTROL_POLL_INTERVAL", "2")))
DB_PATH = Path(os.environ.get("HERALDOR_DB_PATH", "/state/heraldor.sqlite3"))
SNAPSHOT_PATH = Path(
    os.environ.get("HERALDOR_SNAPSHOT_PATH", "/state/backup/heraldor.sqlite3")
)
SERVANT_OBJECTIVE = "zapeg_hsvc"
SERVANT_SCORE_HOLDER = "#total"
SERVANT_WORLD_OBJECTIVE = "zh_svc_world"
SERVANT_WORLD_HOLDER = "#world"
PLAYER_NAME_RE = re.compile(r"^[A-Za-z0-9_]{1,16}$")
CONTROL_STORAGE = "zapeg:heraldor"


@dataclass(frozen=True)
class ControlOutcome:
    event_id: str
    status: str
    message: str

# Olasılıklar: her CHECK_INTERVAL'da zar atılır (gündüz değerleri)
P_WHISPER = float(os.environ.get("P_WHISPER", "0.002"))
P_GLOBAL = float(os.environ.get("P_GLOBAL", "0.0005"))
P_DISCORD = float(os.environ.get("P_DISCORD", "0.0003"))
P_SHADOWS = float(os.environ.get("P_SHADOWS", "0.0002"))

WHISPERS = [
    "arkana bakma.",
    "kazma sesini duyuyorum. hep duyuyorum.",
    "o meşaleyi ben söndürmedim.",
    "burayı kazmamalıydın.",
    "yalnız değilsin. hiç olmadın.",
    "gölgen benim yanımda kalıyor artık.",
    "kapıyı açık bıraktın.",
    "yatağın soğuk. benimki gibi.",
    "adımı söyleme.",
    "seni sayıyorum.",
]

GLOBALS_ = [
    "O kule benimdi.",
    "Kaybettiğiniz her eşya bana geliyor.",
    "Kaç kişi olduğunuzu saydım. Bir fazla çıktık.",
    "Beni hatırlayanlar artık uyumuyor.",
    "Işıklarınız güzelmiş. Şimdilik.",
    "Uyuyunca daha sessiz oluyorsunuz.",
]

DISCORDS = [
    "sunucu hiç kapanmıyor sanıyorsunuz. ben hiç uyumuyorum.",
    "birinizin gölgesi kendisinden önce geldi.",
    "bu kanalı da görüyorum.",
    "biriniz bu gece geç saate kadar oynayacak. biliyorum.",
    "🕯",
]

OBFUS = "kelimeler kayboluyor"  # §k ile bozulan kısım


def rcon_password() -> str:
    """Explicit override, otherwise the live secret generated by itzg/mc."""
    if RCON_PASSWORD_OVERRIDE:
        return RCON_PASSWORD_OVERRIDE
    try:
        for raw in RCON_ENV_FILE.read_text(encoding="utf-8").splitlines():
            key, sep, value = raw.partition("=")
            if sep and key.strip() == "password" and value.strip():
                return value.strip().strip("\"'")
    except OSError as exc:
        raise RuntimeError(f"RCON parola dosyası okunamadı: {RCON_ENV_FILE}") from exc
    raise RuntimeError(f"RCON parolası bulunamadı: {RCON_ENV_FILE}")


def rcon_many(commands: list[str]) -> list[str]:
    with MCRcon(RCON_HOST, rcon_password(), port=RCON_PORT) as r:
        return [r.command(command) for command in commands]


def rcon(cmd: str) -> str:
    return rcon_many([cmd])[0]


def online_players() -> list:
    try:
        out = rcon("list")
        if ":" in out:
            names = out.split(":", 1)[1].strip()
            return [
                name
                for raw in names.split(",")
                if (name := raw.strip()) and PLAYER_NAME_RE.fullmatch(name)
            ]
    except Exception as e:
        print(f"[heraldor] list hata: {e}")
    return []


def is_night() -> bool:
    try:
        out = rcon("time query daytime")  # "The time is 14500"
        t = int("".join(ch for ch in out if ch.isdigit()) or 0)
        return 13000 <= t <= 23000
    except Exception:
        return False


def _control_event_shape(request: ControlRequest) -> tuple[str, str, bool]:
    if request.action in {"phase_start", "phase_advance"}:
        return "director_phase", "campaign", False
    if request.action == "pause":
        return "director_pause", "campaign", False
    if request.action == "resume":
        return "director_resume", "campaign", False
    if request.action in {"scene_rehearse", "scene_trigger"}:
        return "director_scene", "directed", request.action == "scene_rehearse"
    if request.action == "cancel":
        return "director_cancel", "operator", False
    return "director_status", "operator", False


def _reject_control(
    director: DirectorStore,
    request: ControlRequest,
    reason: str,
    *,
    status: str = "rejected",
    now: int,
) -> ControlOutcome:
    kind, category, rehearsal = _control_event_shape(request)
    existing = director.control_event_status(request.event_id)
    if existing == "reserved":
        director.finish_reserved_control(
            request.event_id, status=status, error=reason, now=now
        )
    elif existing is None:
        director.record_control_event(
            request,
            kind=kind,
            category=category,
            status=status,
            subject=request.target,
            rehearsal=rehearsal,
            error=reason,
            now=now,
        )
    terminal = director.control_event_status(request.event_id) or status
    return ControlOutcome(request.event_id, terminal, reason)


def process_control_request(
    director: DirectorStore,
    request: ControlRequest,
    *,
    observed_world_token: int | str,
    now: int | None = None,
) -> ControlOutcome:
    """Validate, persist and execute one strict high-level Director request."""

    timestamp = int(director.clock() if now is None else now)
    existing = director.control_event_status(request.event_id)
    if existing == "attempting":
        # A single daemon owns the state lock, so an attempt found at the start
        # of a later mailbox poll is an unresolved prior call, never concurrent.
        director.finish_attempt(
            request.event_id,
            delivered=None,
            error="prior control attempt ended without a terminal result",
            now=timestamp,
        )
        existing = director.control_event_status(request.event_id)
    if existing and existing != "reserved":
        # Retry a previously failed snapshot write before acknowledging and
        # removing the exact mailbox value.
        director.backup_snapshot()
        return ControlOutcome(
            request.event_id,
            existing,
            f"request already {existing}; it was not replayed",
        )
    if request.expires_at <= timestamp:
        return _reject_control(
            director,
            request,
            "request expired before the Director accepted it",
            status="suppressed_expired",
            now=timestamp,
        )
    if request.expires_at > timestamp + CONTROL_TOKEN_MAX_FUTURE_SECONDS:
        return _reject_control(
            director,
            request,
            "request expiry is outside the allowed window",
            now=timestamp,
        )
    if str(observed_world_token) != request.world_token:
        return _reject_control(
            director,
            request,
            "request belongs to a different Minecraft world",
            now=timestamp,
        )

    state = director.campaign_state(request.world_token)
    kind, category, rehearsal = _control_event_shape(request)

    if request.action == "status":
        message = (
            f"phase={state.phase}, paused={'yes' if state.paused else 'no'}, "
            f"world={state.world_token}"
        )
        record = director.record_control_event(
            request,
            kind=kind,
            category=category,
            status="delivered",
            payload={"phase": state.phase, "paused": state.paused},
            now=timestamp,
        )
        return ControlOutcome(record.event_id, record.status, message)

    if request.action == "pause":
        if state.paused:
            return _reject_control(
                director, request, "campaign is already paused", now=timestamp
            )
        record = director.record_control_event(
            request,
            kind=kind,
            category=category,
            status="delivered",
            payload={"phase": state.phase},
            now=timestamp,
        )
        return ControlOutcome(record.event_id, record.status, "campaign paused")

    if request.action == "resume":
        if not state.paused:
            return _reject_control(
                director, request, "campaign is not paused", now=timestamp
            )
        record = director.record_control_event(
            request,
            kind=kind,
            category=category,
            status="delivered",
            payload={"phase": state.phase},
            now=timestamp,
        )
        return ControlOutcome(record.event_id, record.status, "campaign resumed")

    if request.action in {"phase_start", "phase_advance"}:
        current_index = CONTROL_PHASES.index(state.phase)
        if request.action == "phase_advance":
            if current_index == len(CONTROL_PHASES) - 1:
                return _reject_control(
                    director,
                    request,
                    "manifestation is already the highest released phase",
                    now=timestamp,
                )
            desired = CONTROL_PHASES[current_index + 1]
        else:
            desired = request.argument
            desired_index = CONTROL_PHASES.index(desired)
            if desired_index == current_index:
                return _reject_control(
                    director,
                    request,
                    f"campaign is already in phase {desired}",
                    now=timestamp,
                )
            if desired_index < current_index:
                return _reject_control(
                    director,
                    request,
                    f"phase cannot move backward from {state.phase} to {desired}",
                    now=timestamp,
                )
        record = director.record_control_event(
            request,
            kind=kind,
            category=category,
            status="delivered",
            payload={"previous_phase": state.phase, "phase": desired},
            now=timestamp,
        )
        return ControlOutcome(
            record.event_id, record.status, f"campaign phase is now {desired}"
        )

    if request.action in {"scene_rehearse", "scene_trigger"}:
        minimum = CONTROL_SCENE_PROFILE_PHASES[request.argument]
        if not state.allows_profile(request.argument):
            return _reject_control(
                director,
                request,
                f"{request.argument} requires campaign phase {minimum} or later",
                now=timestamp,
            )
        if request.action == "scene_trigger" and state.paused:
            return _reject_control(
                director,
                request,
                "campaign is paused; new live scenes are suppressed",
                now=timestamp,
            )

    payload: dict[str, object] = {}
    if request.action in {"scene_rehearse", "scene_trigger"}:
        payload = {
            "profile": request.argument,
            "target": request.target,
        }
        if request.action == "scene_trigger":
            payload["runtime_event_id"] = request.event_id
        else:
            payload["runtime_event_id_policy"] = "runtime_generated"
    record = director.record_control_event(
        request,
        kind=kind,
        category=category,
        status="reserved",
        payload=payload,
        subject=request.target,
        rehearsal=rehearsal,
        now=timestamp,
    )
    if record.status != "reserved":
        return ControlOutcome(
            record.event_id,
            record.status,
            f"request already {record.status}; it was not replayed",
        )
    if not director.mark_attempting(record.event_id, now=timestamp):
        terminal = director.control_event_status(record.event_id) or "ambiguous"
        return ControlOutcome(record.event_id, terminal, "request could not be claimed")

    if request.action == "cancel":
        command = "zapegscene cancel-all"
    elif request.action == "scene_rehearse":
        command = f"zapegscene rehearse {request.target} {request.argument}"
    else:
        ttl_ticks = scene_ttl_ticks(request.argument, state.phase)
        command = (
            f"zapegscene trigger {request.target} {request.event_id} "
            f"{request.argument} {ttl_ticks}"
        )

    try:
        output = str(rcon(command)).strip()
    except Exception as exc:
        error = f"runtime response was uncertain: {exc}"
        director.finish_attempt(record.event_id, delivered=None, error=error)
        return ControlOutcome(record.event_id, "ambiguous", error)

    success = (
        output.startswith("scene dispatched event=")
        if request.action != "cancel"
        else output in {"scene cancelled", "active=0"}
    )
    director.finish_attempt(
        record.event_id,
        delivered=success,
        error=None if success else f"runtime rejected request: {output}",
    )
    if success:
        message = output
        return ControlOutcome(record.event_id, "delivered", message)
    return ControlOutcome(
        record.event_id, "failed", f"runtime rejected request: {output[:180]}"
    )


def _clear_control_request(request: ControlRequest) -> None:
    encoded = json.dumps(request.token, ensure_ascii=True)
    rcon(
        f"execute if data storage {CONTROL_STORAGE} "
        f"{{control_request:{encoded}}} run data remove storage "
        f"{CONTROL_STORAGE} control_request"
    )


def _reply_to_control_operator(request: ControlRequest, outcome: ControlOutcome) -> None:
    text = f"[Heraldor Director] {outcome.message} ({outcome.status})"
    if request.operator == "console":
        print(f"[heraldor] {text}")
        return
    if not PLAYER_NAME_RE.fullmatch(request.operator):
        return
    color = (
        "red"
        if outcome.status in {"failed", "rejected", "ambiguous", "suppressed_expired"}
        else "gray"
    )
    payload = json.dumps({"text": text, "color": color}, ensure_ascii=False)
    try:
        rcon(f"tellraw {request.operator} {payload}")
    except Exception as exc:
        print(f"[heraldor] Director yanıtı oyuncuya iletilemedi: {exc}")


def poll_control_request(director: DirectorStore) -> ControlOutcome | None:
    world_command = (
        f"scoreboard players get {SERVANT_WORLD_HOLDER} {SERVANT_WORLD_OBJECTIVE}"
    )
    world_before_output, storage_output, world_after_output = rcon_many(
        [
            world_command,
            f"data get storage {CONTROL_STORAGE} control_request",
            world_command,
        ]
    )
    world_before = parse_score_output(world_before_output, SERVANT_WORLD_OBJECTIVE)
    world_after = parse_score_output(world_after_output, SERVANT_WORLD_OBJECTIVE)
    if world_before is None or world_before != world_after:
        return None

    token = extract_control_request_token(storage_output)
    if token is None:
        return None
    try:
        request = parse_control_request(token)
    except ValueError as exc:
        # Never remove a value we cannot parse and audit exactly. The host can
        # inspect and conditionally clear this one slot using the runbook.
        print(f"[heraldor] Director posta kutusu geçersiz; güvenli kapandı: {exc}")
        return None

    outcome = process_control_request(
        director,
        request,
        observed_world_token=world_before,
    )
    try:
        _clear_control_request(request)
    except Exception as exc:
        # The deterministic SQLite row is the replay barrier. If the exact
        # mailbox value remains, the next poll acknowledges it without replay.
        print(f"[heraldor] Director isteği onay kutusundan silinemedi: {exc}")
    _reply_to_control_operator(request, outcome)
    print(
        f"[heraldor] Director request={request.event_id} action={request.action} "
        f"operator={request.operator} status={outcome.status}"
    )
    return outcome


def llm_line(kind: str) -> str | None:
    if not USE_LLM:
        return None
    try:
        from openai import OpenAI

        client = OpenAI(
            base_url=os.environ.get("LLM_BASE_URL", "https://api.openai.com/v1"),
            api_key=os.environ.get("LLM_API_KEY", "none"),
        )
        resp = client.chat.completions.create(
            model=os.environ.get("LLM_MODEL", "gpt-4o-mini"),
            max_tokens=40,
            temperature=1.1,
            timeout=20,
            messages=[
                {
                    "role": "user",
                    "content": (
                        "Heraldor adında, Minecraft sunucusunda yaşayan Herobrine türü "
                        "tekinsiz bir varlıksın. Türkçe, TEK cümlelik, kısa ve rahatsız "
                        f"edici bir {kind} cümlesi yaz. Şiddet/tehdit yok — tekinsizlik var. "
                        "Tırnak kullanma."
                    ),
                }
            ],
        )
        line = (resp.choices[0].message.content or "").strip().replace('"', "'")
        return line[:140] or None
    except Exception as e:
        print(f"[heraldor] llm hata (havuz kullanılacak): {e}")
        return None


def whisper(player: str) -> None:
    line = llm_line("fısıltı") or random.choice(WHISPERS)
    payload = json.dumps(
        [
            "",
            {"text": line + " ", "color": "dark_gray", "italic": True},
            {"text": OBFUS, "color": "dark_gray", "obfuscated": True},
        ],
        ensure_ascii=False,
    )
    rcon(f"tellraw {player} {payload}")
    snd = random.choice(
        ["minecraft:ambient.cave", "minecraft:entity.enderman.stare", "minecraft:block.sculk_sensor.clicking"]
    )
    rcon(f"execute at {player} run playsound {snd} hostile {player} ~ ~ ~ 0.7 0.5")
    print(f"[heraldor] whisper -> {player}: {line}")


def global_msg() -> None:
    line = llm_line("herkese açık kısa mesaj") or random.choice(GLOBALS_)
    payload = json.dumps(
        [
            "",
            {"text": "Heraldor", "color": "dark_red", "bold": True},
            {"text": " " + line, "color": "gray", "italic": True},
        ],
        ensure_ascii=False,
    )
    rcon(f"tellraw @a {payload}")
    rcon(
        "execute as @a at @s run playsound "
        "minecraft:ambient.basalt_deltas.mood hostile @s ~ ~ ~ 0.5 0.6"
    )
    print(f"[heraldor] global: {line}")


def discord_msg() -> None:
    if not WEBHOOK:
        raise RuntimeError("Discord webhook is not configured")
    line = llm_line("Discord kanalına yazılmış tekinsiz mesaj") or random.choice(DISCORDS)
    req = urllib.request.Request(
        WEBHOOK,
        data=json.dumps({"content": line, "username": "Heraldor"}).encode("utf-8"),
        headers={"Content-Type": "application/json", "User-Agent": "heraldor/2.0"},
    )
    urllib.request.urlopen(req, timeout=15).read()
    print(f"[heraldor] discord: {line}")


def shadows(player: str) -> None:
    """Gece yarısı 30 sn'lik vex tacizi — kendiliğinden yok olur, grief yok."""
    name = json.dumps({"text": "Heraldor'un Gölgesi", "color": "dark_gray"}, ensure_ascii=False)
    name_snbt = json.dumps(name, ensure_ascii=False)
    for _ in range(3):
        rcon(
            f"execute at {player} run summon minecraft:vex ~ ~1 ~ "
            f"{{CustomName:{name_snbt},LifeTicks:600,Silent:1b}}"
        )
    rcon(f"execute at {player} run playsound minecraft:entity.vex.charge hostile {player} ~ ~ ~ 1 0.6")
    payload = json.dumps(
        [{"text": "gölgelerim seni buldu.", "color": "dark_gray", "italic": True}],
        ensure_ascii=False,
    )
    rcon(f"tellraw {player} {payload}")
    print(f"[heraldor] shadows -> {player}")


def dispatch_ambient(director: DirectorStore, reservation: Reservation) -> None:
    """Attempt an irreversible side effect once; crashes become ambiguous."""

    if not director.mark_attempting(reservation.event_id):
        return
    try:
        if reservation.kind == "whisper" and reservation.subject:
            whisper(reservation.subject)
        elif reservation.kind == "global":
            global_msg()
        elif reservation.kind == "discord":
            discord_msg()
        elif reservation.kind == "shadows" and reservation.subject:
            shadows(reservation.subject)
        else:
            raise RuntimeError(f"geçersiz olay: {reservation.kind}")
    except Exception as exc:
        director.finish_attempt(reservation.event_id, delivered=None, error=str(exc))
        print(f"[heraldor] {reservation.kind} gönderilemedi: {exc}")
    else:
        director.finish_attempt(reservation.event_id, delivered=True)


def ambient_cycle(
    director: DirectorStore, world_token: int | str | None = None
) -> None:
    """Roll all rare candidates, but permit at most one event per cycle."""

    if world_token is None:
        return
    campaign = director.campaign_state(world_token)
    if campaign.phase == "dormant" or campaign.paused:
        return

    players = online_players()
    night = is_night() if players else False
    multiplier = 3.0 if night else 1.0
    candidates: list[tuple[str, str | None]] = []

    if players and random.random() < P_WHISPER * multiplier:
        candidates.append(("whisper", random.choice(players)))
    if players and random.random() < P_GLOBAL * multiplier:
        candidates.append(("global", None))
    if WEBHOOK and random.random() < P_DISCORD:
        candidates.append(("discord", None))
    if EVENTS and players and night and random.random() < P_SHADOWS:
        candidates.append(("shadows", random.choice(players)))

    if not candidates:
        return
    kind, subject = random.choice(candidates)
    reservation = director.reserve_ambient(
        kind, subject=subject, world_token=world_token
    )
    if reservation:
        dispatch_ambient(director, reservation)


def poll_servant_score(director: DirectorStore):
    world_command = (
        f"scoreboard players get {SERVANT_WORLD_HOLDER} {SERVANT_WORLD_OBJECTIVE}"
    )
    world_before_output, score_output, world_after_output = rcon_many(
        [
            world_command,
            f"scoreboard players get {SERVANT_SCORE_HOLDER} {SERVANT_OBJECTIVE}",
            world_command,
        ]
    )
    world_before = parse_score_output(world_before_output, SERVANT_WORLD_OBJECTIVE)
    world_after = parse_score_output(world_after_output, SERVANT_WORLD_OBJECTIVE)
    score = parse_score_output(score_output, SERVANT_OBJECTIVE)
    if score is None or world_before is None or world_before != world_after:
        return None

    result = director.ingest_servant_score(score, world_token=world_before)
    if result.victory_event_ids:
        print(
            f"[heraldor] hizmetkâr zaferleri işlendi: "
            f"{result.previous_high_water} -> {result.high_water}"
        )
    if result.story_event_id:
        output_state = result.story_output_status or "çıkış durumu bilinmiyor"
        print(
            "[heraldor] hikâye eşiği kaydedildi: "
            f"{result.story_event_id}; ses kimliği=servants_after_three_v1; "
            f"{output_state}"
        )
    return result, score, world_before


def _world_token_from_servant_poll(polled) -> int | None:
    """Never carry a prior world's token through an unstable/failed poll."""

    return int(polled[2]) if polled else None


def run_daemon() -> None:
    print(
        f"[heraldor] uyanıyor — ambient={CHECK_INTERVAL}s, minion={MINION_POLL_INTERVAL}s, "
        f"director={CONTROL_POLL_INTERVAL}s, "
        f"webhook={'var' if WEBHOOK else 'yok'}, events={EVENTS}, llm={USE_LLM}, "
        f"voice={VOICE_ENABLED}, db={DB_PATH}"
    )
    with (
        DirectorStateLock(Path(str(DB_PATH) + ".lock")),
        DirectorStore(
            DB_PATH,
            snapshot_path=SNAPSHOT_PATH,
            audio_sink_enabled=VOICE_ENABLED,
        ) as director,
    ):
        director.backup_snapshot()
        next_ambient = time.monotonic() + CHECK_INTERVAL
        next_minion_poll = time.monotonic()
        next_control_poll = time.monotonic()
        active_world_token: int | None = None
        last_score_anomaly: tuple[str, int, int] | None = None

        while True:
            # Control has priority when schedules coincide, so a queued pause
            # cannot be overtaken by threshold output during startup/recovery.
            now = time.monotonic()
            if now >= next_control_poll:
                next_control_poll = now + CONTROL_POLL_INTERVAL
                try:
                    poll_control_request(director)
                except Exception as exc:
                    print(f"[heraldor] Director posta kutusu okunamadı: {exc}")

            now = time.monotonic()
            if now >= next_minion_poll:
                next_minion_poll = now + MINION_POLL_INTERVAL
                try:
                    polled = poll_servant_score(director)
                    active_world_token = _world_token_from_servant_poll(polled)
                    if polled and (polled[0].regression or polled[0].quarantined):
                        result, observed_score, _world_token = polled
                        kind = "regression" if result.regression else "implausible_jump"
                        anomaly = (kind, result.high_water, observed_score)
                        if anomaly != last_score_anomaly:
                            label = "geriledi" if result.regression else "mantıksız sıçradı"
                            print(
                                f"[heraldor] hizmetkâr skoru {label}; güvenli biçimde "
                                f"karantinaya alındı: kayıt={anomaly[1]}, görülen={anomaly[2]}"
                            )
                            last_score_anomaly = anomaly
                    elif polled:
                        last_score_anomaly = None
                except Exception as exc:
                    active_world_token = _world_token_from_servant_poll(None)
                    print(f"[heraldor] hizmetkâr skoru okunamadı: {exc}")

            now = time.monotonic()
            if now >= next_ambient:
                next_ambient = now + CHECK_INTERVAL
                try:
                    ambient_cycle(director, active_world_token)
                except Exception as exc:
                    print(f"[heraldor] atmosfer döngüsü hata: {exc}")

            delay = (
                min(next_ambient, next_minion_poll, next_control_poll)
                - time.monotonic()
            )
            time.sleep(max(0.25, min(delay, 5.0)))


def run_admin(command: str) -> None:
    if command == "restore-snapshot":
        restore_snapshot(DB_PATH, SNAPSHOT_PATH)
        print(f"[heraldor] tutarlı yedek canlı DB'ye geri yüklendi: {SNAPSHOT_PATH}")
        return

    # Admin readers may run beside the daemon; they must never classify the
    # daemon's currently-attempting side effect as a crashed one.
    with DirectorStore(
        DB_PATH,
        snapshot_path=SNAPSHOT_PATH,
        recover_interrupted_attempts=False,
    ) as director:
        if command == "status":
            print(json.dumps(director.status(), ensure_ascii=False, indent=2))
        elif command == "snapshot":
            director.backup_snapshot()
            print(f"[heraldor] tutarlı yedek yazıldı: {SNAPSHOT_PATH}")
        elif command == "voice-rehearse":
            event_id = director.enqueue_audio_rehearsal()
            print(
                "[heraldor] ses provası sıraya alındı; iki dakika içinde yalnız "
                f"test kanalında çalabilir: {event_id}"
            )
        else:
            raise ValueError(f"bilinmeyen admin komutu: {command}")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Heraldor persistent director")
    subparsers = parser.add_subparsers(dest="mode")
    admin = subparsers.add_parser("admin", help="host-only state inspection")
    admin.add_argument(
        "command",
        choices=("status", "snapshot", "restore-snapshot", "voice-rehearse"),
    )
    args = parser.parse_args(argv)

    if args.mode == "admin":
        run_admin(args.command)
    else:
        run_daemon()


if __name__ == "__main__":
    main()
